language: generic

env:
  matrix:
  - CONDA_PY=3.7 CONDA_NPY=1.17
  - CONDA_PY=3.8 CONDA_NPY=1.18
  - CONDA_PY=3.9 CONDA_NPY=1.19

before_install:
  - sudo apt-get update
  - sudo apt-get install gfortran
  - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda install -q numpy=$CONDA_NPY conda-build

install:
  - conda build --python=$CONDA_PY --numpy=$CONDA_NPY .

