{% set data = load_setuptools()%}
package:
  name: capytaine
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - numpy
    - meshmagick >=1.1

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENCE
  summary: {{data.get('description')}}
