package:
  name: capytaine
  version: 0.0

source:
  path: /home/ancellin/capytaine/

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy

test:
  imports:
    - capytaine

about:
  home: https://github.com/mancellin/capytaine
  license: GPL
  license_file: LICENSE
