package:
  name: capytaine
  version: 0.1

source:
  path: /home/ancellin/capytaine/

requirements:
  build:
    - python
    - setuptools
	- numpy

  run:
    - python
    - numpy

# test:
#   imports:
#     - capytaine

about:
  home: https://github.com/mancellin/capytaine
  license: GPL
  license_file: LICENSE
