{% set data = load_setup_py_data()%}
package:
  name: capytaine
  version: {{data.get('version')}}

source:
  path: ../

requirements:
  build:
    - python
    - setuptools
    - numpy
    - sphinx
  run:
    - python
    - attrs
    - libgfortran=3
    - matplotlib
    - numpy
    - pandas
    - scipy
    - vtk
    - xarray

build:
  entry_points:
    - capytaine = capytaine.cli:main

about:
  home: {{data.get('url')}}
  license: {{data.get('license')}}
  license_file: LICENSE
  summary: {{data.get('description')}}
